"""女性情趣用品品类的演示数据 — 让工具无需API即可体验完整功能"""

DEMO_PRODUCTS = [
    {
        "asin": "B0DEMO001",
        "title": "Womanizer Premium 2 - 空气脉冲按摩器 带智能静音技术",
        "brand": "Womanizer",
        "price": 149.99,
        "currency": "USD",
        "rating": 4.5,
        "review_count": 3842,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO001",
        "category": "女性情趣用品",
        "bsr_category": "#1 in Female Sex Toys",
        "description": "Womanizer Premium 2 采用专利 Pleasure Air 技术，提供无接触的阴蒂刺激。智能静音技术使其成为市场上最安静的空气脉冲设备之一。6种强度级别和自动关机功能。",
        "bullet_points": [
            "Pleasure Air 技术：无接触刺激",
            "智能静音技术：比前代安静50%",
            "6种强度级别，满足不同敏感度",
            "Autopilot 自动模式：自动变换强度",
            "USB-C 充电，续航4小时",
            "100%防水，可在沐浴时使用"
        ],
        "specifications": {"尺寸": "18.5 x 5.5 cm", "重量": "160g", "材质": "医用级硅胶", "充电": "USB-C", "续航": "4小时"},
        "dimensions": "18.5 x 5.5 x 5.5 cm",
        "weight": "160g",
        "color_options": ["紫色", "红色", "黑色", "白色"],
        "material": "医用级硅胶 + ABS塑料",
        "features": ["空气脉冲", "智能静音", "Autopilot模式", "防水IPX7", "旅行锁"],
        "estimated_monthly_sales": 3500
    },
    {
        "asin": "B0DEMO002",
        "title": "Lelo Sila Cruise - 空气脉冲阴蒂按摩器",
        "brand": "LELO",
        "price": 129.00,
        "currency": "USD",
        "rating": 4.3,
        "review_count": 2156,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO002",
        "category": "女性情趣用品",
        "bsr_category": "#3 in Female Sex Toys",
        "description": "Lelo Sila Cruise 采用 Cruise Control 技术，按压时自动增强动力。独特 Sonic Wave 技术提供深层、有针对性的刺激。",
        "bullet_points": [
            "Sonic Wave 声波技术",
            "Cruise Control 压力感应增强技术",
            "8种强度模式",
            "100%防水",
            "丝绒硅胶触感",
            "USB充电，续航2小时"
        ],
        "specifications": {"尺寸": "17.3 x 5.2 cm", "重量": "145g", "材质": "医用级硅胶", "充电": "USB磁吸", "续航": "2小时"},
        "dimensions": "17.3 x 5.2 x 5.2 cm",
        "weight": "145g",
        "color_options": ["玫瑰金", "深紫", "薄荷绿"],
        "material": "医用级硅胶 + ABS塑料",
        "features": ["声波技术", "压力感应", "8种模式", "防水", "静音"],
        "estimated_monthly_sales": 2800
    },
    {
        "asin": "B0DEMO003",
        "title": "Satisfyer Pro 2 Generation 3 - 空气脉冲刺激器",
        "brand": "Satisfyer",
        "price": 49.95,
        "currency": "USD",
        "rating": 4.4,
        "review_count": 15680,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO003",
        "category": "女性情趣用品",
        "bsr_category": "#1 in Clitoral Stimulators",
        "description": "Satisfyer Pro 2 是最畅销的空气脉冲产品之一。11种强度级别，性价比极高。",
        "bullet_points": [
            "Air Pulse 空气脉冲技术",
            "11种强度级别",
            "100%防水",
            "超静音电机",
            "Partner Link 功能：支持远程控制",
            "价格亲民，入门首选"
        ],
        "specifications": {"尺寸": "16.5 x 5.0 cm", "重量": "120g", "材质": "硅胶 + ABS", "充电": "USB", "续航": "3小时"},
        "dimensions": "16.5 x 5.0 x 5.0 cm",
        "weight": "120g",
        "color_options": ["粉色", "紫色", "蓝色", "黑色", "白色"],
        "material": "硅胶 + ABS塑料",
        "features": ["空气脉冲", "11种模式", "防水", "远程控制", "静音"],
        "estimated_monthly_sales": 8000
    },
    {
        "asin": "B0DEMO004",
        "title": "Lovense Domi 2 - 智能震动棒 支持APP远程控制",
        "brand": "Lovense",
        "price": 89.00,
        "currency": "USD",
        "rating": 4.6,
        "review_count": 4521,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO004",
        "category": "女性情趣用品",
        "bsr_category": "#2 in Vibrators",
        "description": "Lovense Domi 2 是强大的智能震动棒，通过手机APP可远程控制。非常适合情侣互动。",
        "bullet_points": [
            "超强震动马达",
            "蓝牙APP远程控制",
            "支持全球远程连接",
            "可与其他Lovense设备同步",
            "磁吸充电",
            "低噪音设计"
        ],
        "specifications": {"尺寸": "21.0 x 4.0 cm", "重量": "200g", "材质": "医用级硅胶", "充电": "USB磁吸", "续航": "3小时"},
        "dimensions": "21.0 x 4.0 x 4.0 cm",
        "weight": "200g",
        "color_options": ["粉色", "紫色", "黑色"],
        "material": "医用级硅胶 + ABS塑料",
        "features": ["APP控制", "远程连接", "超强震动", "磁吸充电", "静音"],
        "estimated_monthly_sales": 4200
    },
    {
        "asin": "B0DEMO005",
        "title": "Dame Products Eva II - 可穿戴情侣震动器",
        "brand": "Dame Products",
        "price": 129.00,
        "currency": "USD",
        "rating": 4.1,
        "review_count": 892,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO005",
        "category": "女性情趣用品",
        "bsr_category": "#10 in Couples Toys",
        "description": "Eva II 是专为情侣设计的可穿戴震动器，独特的翅膀设计使其在性爱过程中无需手持。",
        "bullet_points": [
            "免手持设计，适合情侣使用",
            "双手自由，使用时不妨碍亲密接触",
            "柔性翅膀贴合身体曲线",
            "3种震动模式",
            "医用级硅胶，安全亲肤",
            "充电2小时，续航1小时"
        ],
        "specifications": {"尺寸": "8.5 x 6.2 x 3.0 cm", "重量": "65g", "材质": "医用级硅胶", "充电": "USB", "续航": "1小时"},
        "dimensions": "8.5 x 6.2 x 3.0 cm",
        "weight": "65g",
        "color_options": ["珊瑚粉", "紫色"],
        "material": "医用级硅胶",
        "features": ["可穿戴", "免手持", "情侣使用", "防水", "安静"],
        "estimated_monthly_sales": 1200
    },
    {
        "asin": "B0DEMO006",
        "title": "We-Vibe Melt - 空气脉冲远程控制按摩器",
        "brand": "We-Vibe",
        "price": 119.00,
        "currency": "USD",
        "rating": 4.2,
        "review_count": 1450,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO006",
        "category": "女性情趣用品",
        "bsr_category": "#5 in Clitoral Stimulators",
        "description": "We-Vibe Melt 结合了空气脉冲技术和远程控制功能，可通过APP或遥控器操作。",
        "bullet_points": [
            "We-Vibe 专属声波技术",
            "蓝牙APP远程控制",
            "12种强度级别",
            "超薄设计，贴合适中",
            "100%防水",
            "情侣远程互动"
        ],
        "specifications": {"尺寸": "14.0 x 4.5 x 4.0 cm", "重量": "95g", "材质": "医用级硅胶", "充电": "USB磁吸", "续航": "2.5小时"},
        "dimensions": "14.0 x 4.5 x 4.0 cm",
        "weight": "95g",
        "color_options": ["酒红", "紫色", "黑色"],
        "material": "医用级硅胶 + ABS",
        "features": ["空气脉冲", "APP控制", "12种模式", "防水", "远程互动"],
        "estimated_monthly_sales": 1900
    },
    {
        "asin": "B0DEMO007",
        "title": "Fun Factory Miss Bi - 弯曲型G点震动棒",
        "brand": "Fun Factory",
        "price": 79.99,
        "currency": "USD",
        "rating": 4.0,
        "review_count": 2340,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO007",
        "category": "女性情趣用品",
        "bsr_category": "#6 in G-Spot Vibrators",
        "description": "Miss Bi 独特的弯曲角度专为G点刺激设计，德国设计制造，品质保证。",
        "bullet_points": [
            "独特弯曲角度，精准G点刺激",
            "德国设计制造",
            "两种马达，双倍快感",
            "12种模式",
            "人体工学设计",
            "医用级硅胶，无味安全"
        ],
        "specifications": {"尺寸": "20.0 x 3.5 cm", "重量": "180g", "材质": "医用级硅胶", "充电": "USB", "续航": "2小时"},
        "dimensions": "20.0 x 3.5 x 3.5 cm",
        "weight": "180g",
        "color_options": ["紫色", "蓝绿色", "粉色"],
        "material": "医用级硅胶",
        "features": ["G点刺激", "双马达", "12种模式", "防水", "人体工学"],
        "estimated_monthly_sales": 2100
    },
    {
        "asin": "B0DEMO008",
        "title": "Maude Vibe - 极简设计震动棒",
        "brand": "Maude",
        "price": 45.00,
        "currency": "USD",
        "rating": 4.3,
        "review_count": 3100,
        "main_image": "https://images.unsplash.com/photo-1612817157573-9f0e7b5c5a3b?w=400",
        "product_url": "https://www.amazon.com/dp/B0DEMO008",
        "category": "女性情趣用品",
        "bsr_category": "#4 in Vibrators",
        "description": "Maude Vibe 以极简美学设计为理念，采用低调优雅的设计风格，是入门级的高品质选择。",
        "bullet_points": [
            "极简美学设计",
            "柔软硅胶，亲肤触感",
            "3种强度，简单易用",
            "USB-C充电",
            "100%防水",
            "低调包装，隐私保护"
        ],
        "specifications": {"尺寸": "17.5 x 2.8 cm", "重量": "85g", "材质": "医用级硅胶", "充电": "USB-C", "续航": "2小时"},
        "dimensions": "17.5 x 2.8 x 2.8 cm",
        "weight": "85g",
        "color_options": ["淡粉", "沙色", "灰色", "淡紫"],
        "material": "医用级硅胶",
        "features": ["极简设计", "入门级", "轻巧便携", "USB-C", "静音"],
        "estimated_monthly_sales": 5600
    }
]

DEMO_REVIEWS = {
    "B0DEMO001": [
        {"review_id": "R001", "title": "改变了我的生活", "content": "这个产品简直不可思议。我之前用过很多其他产品，但没有一个能像这款一样。空气脉冲技术确实与众不同，不是单纯的震动。我的唯一抱怨是价格有点高，但品质确实对得起价格。智能静音功能确实很安静，在卧室里几乎听不到声音。", "rating": 5, "date": "2024-06-15", "verified_purchase": True, "helpful_count": 245},
        {"review_id": "R002", "title": "效果很好但噪音比预期大", "content": "产品本身效果很好，但所谓的'智能静音'并没有宣传的那么安静。开到高强度时声音还是很明显的。另外硅胶材质虽然手感好，但容易吸附灰尘和毛发。", "rating": 4, "date": "2024-05-20", "verified_purchase": True, "helpful_count": 89},
        {"review_id": "R003", "title": "按键设计不合理", "content": "使用起来效果不错，但按键设计得太小了，尤其是在使用过程中想要调节强度时很难找到正确的按键。希望下一代产品能有更大的按键或者触控设计。", "rating": 3, "date": "2024-04-10", "verified_purchase": True, "helpful_count": 156},
        {"review_id": "R004", "title": "充电接口需要改进", "content": "充电接口的位置很尴尬，充电线不太容易插紧。而且充电时指示灯在底部，看不到是否在充电。续航时间还行，但希望有快充功能。", "rating": 3, "date": "2024-03-22", "verified_purchase": True, "helpful_count": 67},
        {"review_id": "R005", "title": "完美但需要更人性化的设计", "content": "功能上是很完美的产品，但我觉得产品设计上可以更考虑女性用户的使用习惯。比如开机默认强度太高了，每次都要按很久才能调到适合自己的强度。应该增加记忆功能。", "rating": 4, "date": "2024-02-18", "verified_purchase": True, "helpful_count": 112},
        {"review_id": "R006", "title": "包装不够隐私", "content": "产品很好，但是快递包装上印着品牌名，让人有点尴尬。希望能在包装上更注重隐私保护。", "rating": 4, "date": "2024-01-05", "verified_purchase": True, "helpful_count": 203},
        {"review_id": "R007", "title": "尺寸稍微有点大", "content": "对我来说这个产品的尺寸稍微有点大，握持不是很舒服。如果设计得更小巧一些，使用体验会更好。", "rating": 3, "date": "2024-07-01", "verified_purchase": True, "helpful_count": 45},
        {"review_id": "R008", "title": "用了几次后开始有噪音", "content": "刚买回来时确实很安静，但用了大约10次之后，开始出现一些机械噪音。虽然不影响功能，但体验打了折扣。", "rating": 3, "date": "2024-06-08", "verified_purchase": True, "helpful_count": 78},
        {"review_id": "R009", "title": "清洁起来很麻烦", "content": "虽然说是防水设计，但清洁时水会进到缝隙里，不容易干。时间长了担心会滋生细菌。希望下一款产品能考虑更容易清洁的设计。", "rating": 4, "date": "2024-04-25", "verified_purchase": True, "helpful_count": 134},
        {"review_id": "R010", "title": "对初学者来说强度太高", "content": "这是我第一次使用这类产品，最低档对我来说还是太强了。如果能增加一个更温和的入门级别，或者有渐进的升温功能会更好。", "rating": 3, "date": "2024-03-15", "verified_purchase": True, "helpful_count": 198}
    ],
    "B0DEMO002": [
        {"review_id": "R011", "title": "设计很漂亮但功能一般", "content": "Lelo的设计确实很美，放在床头柜上就像一件艺术品。但实际使用效果没有我想象的那么惊艳。Cruise Control功能听起来很好，但实际上压力增强的效果不太明显。", "rating": 3, "date": "2024-06-20", "verified_purchase": True, "helpful_count": 87},
        {"review_id": "R012", "title": "材质手感极好", "content": "这款产品的硅胶材质是我用过的所有产品里最舒服的，非常柔软丝滑。但价格确实偏高，性价比不如Satisfyer。", "rating": 4, "date": "2024-05-12", "verified_purchase": True, "helpful_count": 56},
        {"review_id": "R013", "title": "续航太短了", "content": "官方说续航4小时，但实际使用大概只有2小时左右。而且充电时间很长，经常想用的时候发现没电了。希望能改进电池续航。", "rating": 3, "date": "2024-04-08", "verified_purchase": True, "helpful_count": 145},
        {"review_id": "R014", "title": "按键容易误触", "content": "操作按钮的位置在握持时会经常被误触，用着用着突然变了模式，很影响体验。按键设计需要重新考虑。", "rating": 3, "date": "2024-03-28", "verified_purchase": True, "helpful_count": 92},
        {"review_id": "R015", "title": "贵但值得", "content": "确实价格很高，但从设计到材质都能感受到品质。送给朋友的礼物，她很喜欢。包装也很高级。", "rating": 5, "date": "2024-02-15", "verified_purchase": True, "helpful_count": 43},
        {"review_id": "R016", "title": "使用时的角度不太对", "content": "人体工学方面还有改进空间。使用时需要找特定的角度才能达到最佳效果，并不是很直观。希望能有更清晰的使用指引。", "rating": 3, "date": "2024-01-20", "verified_purchase": True, "helpful_count": 71},
        {"review_id": "R017", "title": "震动传播范围小", "content": "与其他同价位产品相比，这款的震动传播范围较小，需要非常精确地放置才能有效。", "rating": 3, "date": "2024-07-02", "verified_purchase": True, "helpful_count": 38},
        {"review_id": "R018", "title": "适合外观党", "content": "设计确实一流，磨砂质感和颜色都非常高级。但如果你是注重功能性多于外观的人，其他品牌可能有更好的选择。", "rating": 4, "date": "2024-06-05", "verified_purchase": True, "helpful_count": 29}
    ],
    "B0DEMO003": [
        {"review_id": "R019", "title": "性价比之王", "content": "这个价格能有这样的品质真的很惊喜。效果和Womanizer差不多，但价格只有三分之一。非常适合第一次尝试空气脉冲的人。", "rating": 5, "date": "2024-06-25", "verified_purchase": True, "helpful_count": 312},
        {"review_id": "R020", "title": "质量不稳定", "content": "第一个用了3个月就坏了，好在亚马逊退货方便。换了一个新的目前用了2个月没问题。品控似乎不太稳定。", "rating": 2, "date": "2024-05-30", "verified_purchase": True, "helpful_count": 267},
        {"review_id": "R021", "title": "塑料感太强", "content": "虽然价格便宜，但整体手感塑料感很强，不够高级。而且接缝处能看到明显的模具线，做工不够精细。", "rating": 3, "date": "2024-04-15", "verified_purchase": True, "helpful_count": 89},
        {"review_id": "R022", "title": "入门首选", "content": "作为入门产品非常合适，效果不错价格也合理。但用了一两个月后可能就会想升级到更高端的产品。", "rating": 4, "date": "2024-03-20", "verified_purchase": True, "helpful_count": 134},
        {"review_id": "R023", "title": "声音比想象中大", "content": "在'超静音'这点上宣传有点过了。在安静的房间里用，声音还是很明显的。合租的话会觉得尴尬。", "rating": 3, "date": "2024-02-25", "verified_purchase": True, "helpful_count": 178},
        {"review_id": "R024", "title": "按键太硬", "content": "开关和强度调节按键按下去需要比较大的力气，使用过程中调节不太方便。而且按键反馈不够清晰。", "rating": 3, "date": "2024-01-10", "verified_purchase": True, "helpful_count": 56},
        {"review_id": "R025", "title": "配件容易丢失", "content": "附赠的替换硅胶头太小了，很容易弄丢。希望能设计成一体式的，或者有收纳的地方。", "rating": 3, "date": "2024-07-05", "verified_purchase": True, "helpful_count": 42},
        {"review_id": "R026", "title": "充电口设计差", "content": "充电口在底部而且没有防尘盖，用久了里面容易积灰。充电线也不是标准的USB-C，丢了很难配。", "rating": 2, "date": "2024-06-12", "verified_purchase": True, "helpful_count": 73}
    ],
    "B0DEMO004": [
        {"review_id": "R027", "title": "APP连接不稳定", "content": "远程控制的功能想法很好，但APP经常断连，尤其是在bluetooth信号不好的时候。异地情侣使用时体验大打折扣。", "rating": 3, "date": "2024-06-18", "verified_purchase": True, "helpful_count": 234},
        {"review_id": "R028", "title": "震动很强，噪音也很大", "content": "这款产品的马达确实很强大，但噪音水平也相应很高。在公寓里用担心邻居会听到。希望能有静音模式。", "rating": 3, "date": "2024-05-22", "verified_purchase": True, "helpful_count": 156},
        {"review_id": "R029", "title": "手感偏重", "content": "产品本身有点重，长时间手持会手酸。如果设计更轻便会更符合人体工学。另外表面材质容易出汗时打滑。", "rating": 3, "date": "2024-04-12", "verified_purchase": True, "helpful_count": 87},
        {"review_id": "R030", "title": "改善了情侣关系", "content": "和异地的女朋友一起使用，感觉很特别。APP设计得不错，可以创建播放列表和同步模式。但偶尔会有延迟。", "rating": 4, "date": "2024-03-25", "verified_purchase": True, "helpful_count": 145},
        {"review_id": "R031", "title": "电池不耐用", "content": "用了一年后续航明显下降，从3小时降到不到1小时。电池更换也不方便，是一次性产品这点让我很失望。", "rating": 2, "date": "2024-02-28", "verified_purchase": True, "helpful_count": 112},
        {"review_id": "R032", "title": "材质容易吸附灰尘", "content": "硅胶材质虽然是医用级，但表面很容易吸附毛絮和灰尘，每次用之前都要清洗。希望能有防静电处理。", "rating": 4, "date": "2024-01-15", "verified_purchase": True, "helpful_count": 67}
    ],
    "B0DEMO005": [
        {"review_id": "R033", "title": "概念很好，执行欠佳", "content": "免手持的设计概念很好，但实际上很难固定住。运动中经常移位，需要不断调整，反而影响了体验。", "rating": 2, "date": "2024-06-22", "verified_purchase": True, "helpful_count": 189},
        {"review_id": "R034", "title": "只适合特定体型", "content": "这个产品的佩戴效果很大程度上取决于个人体型。对我来说不太贴合，但对于朋友来说却很合适。应该针对不同体型设计不同尺寸。", "rating": 3, "date": "2024-05-10", "verified_purchase": True, "helpful_count": 123},
        {"review_id": "R035", "title": "续航太短", "content": "一个小时的续航在实际使用中完全不够。加上充电需要2小时，使用体验严重受影响。", "rating": 2, "date": "2024-04-05", "verified_purchase": True, "helpful_count": 98},
        {"review_id": "R036", "title": "感谢设计师的用心", "content": "作为一款为情侣设计的产品，它确实解决了一个实际问题。不需要在亲密时停下来操作设备，让一切都更自然。", "rating": 4, "date": "2024-03-18", "verified_purchase": True, "helpful_count": 67},
        {"review_id": "R037", "title": "声音太大不适合情侣使用", "content": "产品本身的噪音在近距离使用时很明显，反而会打断氛围。如果能更安静就好了。", "rating": 3, "date": "2024-02-20", "verified_purchase": True, "helpful_count": 45}
    ],
    "B0DEMO006": [
        {"review_id": "R038", "title": "远程功能强大", "content": "APP控制功能很强大，连接也比较稳定。但产品本身在使用时贴合度不够好，需要用手辅助定位。", "rating": 3, "date": "2024-06-28", "verified_purchase": True, "helpful_count": 89},
        {"review_id": "R039", "title": "不适合所有姿势", "content": "这款产品在特定姿势下使用效果很好，但如果变换姿势就容易脱落。限制了使用场景的多样性。", "rating": 3, "date": "2024-05-15", "verified_purchase": True, "helpful_count": 67},
        {"review_id": "R040", "title": "硅胶触感顶级", "content": "We-Vibe的硅胶材质是市面上最好的之一，非常柔软舒适。但价格偏高，性价比不如Satisfyer。", "rating": 4, "date": "2024-04-22", "verified_purchase": True, "helpful_count": 34},
        {"review_id": "R041", "title": "强度档位间跨度太大", "content": "12个强度看似很多，但实际相邻档位之间的变化很小，而从低到高的跨度太大，中间的档位不够精细。", "rating": 3, "date": "2024-03-30", "verified_purchase": True, "helpful_count": 56},
        {"review_id": "R042", "title": "适合情侣远程恋爱", "content": "异地恋的救星。APP设计很好，可以视频通话时同步控制。但偶尔会有连接延迟。", "rating": 4, "date": "2024-02-10", "verified_purchase": True, "helpful_count": 112}
    ],
    "B0DEMO007": [
        {"review_id": "R043", "title": "德国品质名不虚传", "content": "做工确实很扎实，手感厚实。弯曲角度对G点刺激很准。但产品有点太硬了，缺乏柔韧性。", "rating": 4, "date": "2024-06-10", "verified_purchase": True, "helpful_count": 78},
        {"review_id": "R044", "title": "设计太大不够精致", "content": "这个产品的设计风格比较粗犷，尺寸偏大且外观不够精致。使用起来也缺乏现代感。希望能有更小巧精致的设计。", "rating": 3, "date": "2024-05-28", "verified_purchase": True, "helpful_count": 92},
        {"review_id": "R045", "title": "操作界面复杂", "content": "多达12种模式的切换很麻烦，每次切换都需要长按，而且没有任何模式名称提示，只能靠记忆。希望能简化操作或增加屏幕显示。", "rating": 3, "date": "2024-04-18", "verified_purchase": True, "helpful_count": 67},
        {"review_id": "R046", "title": "表面纹理有改进空间", "content": "产品表面的纹理虽然增加了视觉效果，但实际使用中反而降低了舒适度。平滑表面对我来说更舒适。", "rating": 3, "date": "2024-03-12", "verified_purchase": True, "helpful_count": 45},
        {"review_id": "R047", "title": "马达声音大", "content": "两个马达同时运转时声音很大，不太适合需要安静环境的人。", "rating": 3, "date": "2024-02-08", "verified_purchase": True, "helpful_count": 56}
    ],
    "B0DEMO008": [
        {"review_id": "R048", "title": "颜值即正义", "content": "设计真的太美了，第一眼就被它简约的外观吸引。放在桌上完全看不出是什么。非常喜欢这种低调不张扬的美学。", "rating": 5, "date": "2024-06-30", "verified_purchase": True, "helpful_count": 167},
        {"review_id": "R049", "title": "功能单一", "content": "虽然设计很美，但只有3种模式，用久了会觉得单调。如果能在保持简洁设计的同时增加更多功能选项就好了。", "rating": 3, "date": "2024-05-25", "verified_purchase": True, "helpful_count": 89},
        {"review_id": "R050", "title": "入门好选择", "content": "很适合对这类产品感到好奇但又不想要那种'看起来很吓人'的设计的人。温和不吓人，是很好的入门选择。", "rating": 4, "date": "2024-04-20", "verified_purchase": True, "helpful_count": 78},
        {"review_id": "R051", "title": "动力不足", "content": "对于已经有一定使用经验的人来说，这款的动力可能不够。最高档也就相当于其他品牌的中档。希望能有更强的马达选项。", "rating": 3, "date": "2024-03-15", "verified_purchase": True, "helpful_count": 134},
        {"review_id": "R052", "title": "尺寸偏小", "content": "产品比较小巧，握持感不错但太短了，有些姿势不太方便使用。如果能稍微加长一点会更好。", "rating": 3, "date": "2024-02-22", "verified_purchase": True, "helpful_count": 56},
        {"review_id": "R053", "title": "USB-C充电好评", "content": "终于有品牌用USB-C了！不需要额外带充电线，真的很方便。其他品牌都应该学习。", "rating": 5, "date": "2024-01-28", "verified_purchase": True, "helpful_count": 45},
        {"review_id": "R054", "title": "包装非常优雅", "content": "包装像高端护肤品，快递盒也没有任何敏感标识。收快递时完全不会有尴尬的感觉。这种细节真的很重要。", "rating": 5, "date": "2024-07-02", "verified_purchase": True, "helpful_count": 89}
    ]
}
